group: unit_test1
hosts: 
  - "172.22.4.61"
port: 9092
topics:
  - 
    Topic: ac.init.metadata.unit_test1
    NumPartitions: 1
    ReplicationFactor: 3
  - 
    Topic: ac.init.txn.unit_test1
    NumPartitions: 8
    ReplicationFactor: 3
  - 
    Topic: ac.init.timeseries.unit_test1
    NumPartitions: 12
    ReplicationFactor: 3